const int switchPin= 11;

void setup()
{
  pinMode(11, INPUT);
  pinMode(2, OUTPUT);
  pinMode(3, OUTPUT);
  pinMode(4, OUTPUT);
  pinMode(5, OUTPUT);
  pinMode(6, OUTPUT);
  pinMode(7, OUTPUT);
  pinMode(8, OUTPUT);
  pinMode(9, OUTPUT);
  pinMode(10, OUTPUT);
}

void loop()
{
  int switchVal;  
  switchVal = digitalRead(switchPin);
  if (switchVal == LOW)
  {
   delay(2200);
   digitalWrite(2, HIGH);
   delay(700);
   digitalWrite(2, LOW);
   digitalWrite(3, HIGH);
   delay(700);
   digitalWrite(3, LOW);
   digitalWrite(4, HIGH);
   delay(200);
   digitalWrite(4, LOW);
   digitalWrite(5, HIGH);
   delay(200);
   digitalWrite(5, LOW);
   digitalWrite(6, HIGH);
   delay(200);
   digitalWrite(6, LOW);
   digitalWrite(7, HIGH);
   delay(200);
   digitalWrite(7, LOW);
   digitalWrite(8, HIGH);
   delay(1400);
   digitalWrite(8, LOW);
   digitalWrite(9, HIGH);
   delay(1100);
   digitalWrite(9, LOW);
   digitalWrite(8, HIGH);
   delay(700);
   digitalWrite(8, LOW);
   digitalWrite(7, HIGH);
   delay(700);
   digitalWrite(7, LOW);
   digitalWrite(6, HIGH);
   delay(200);
   digitalWrite(6, LOW);
   digitalWrite(5, HIGH);
   delay(200);
   digitalWrite(5, LOW);
   digitalWrite(4, HIGH);
   delay(300);
   digitalWrite(4, LOW);
   digitalWrite(3, HIGH);
   delay(300);
   digitalWrite(3, LOW);
   digitalWrite(2, HIGH);
   delay(1500);
   digitalWrite(2, LOW);
   digitalWrite(9, HIGH);
   delay(700);
   digitalWrite(9, LOW);
   digitalWrite(8, HIGH);
   delay(1050);
   digitalWrite(2, HIGH);
   digitalWrite(3, HIGH);
   digitalWrite(4, HIGH);  
   digitalWrite(5, HIGH);  
   digitalWrite(6, HIGH);  
   digitalWrite(7, HIGH); 
   delay(80);
   digitalWrite(2, LOW);
   digitalWrite(3, LOW);
   digitalWrite(4, LOW);  
   digitalWrite(5, LOW);  
   digitalWrite(6, LOW);  
   digitalWrite(7, LOW);  
   digitalWrite(8, LOW);  
   digitalWrite(9, LOW);
   delay(150);
   digitalWrite(7, HIGH);
   delay(700);
   digitalWrite(7, LOW); 
   digitalWrite(6, HIGH);
   delay(50);
   digitalWrite(2, HIGH);
   digitalWrite(3, HIGH);
   digitalWrite(4, HIGH);  
   digitalWrite(5, HIGH);    
   digitalWrite(7, HIGH);  
   digitalWrite(8, HIGH);  
   digitalWrite(9, HIGH);   
   delay(80);
   digitalWrite(2, LOW);
   digitalWrite(3, LOW);
   digitalWrite(4, LOW);  
   digitalWrite(5, LOW);  
   digitalWrite(6, LOW);  
   digitalWrite(7, LOW);  
   digitalWrite(8, LOW);  
   digitalWrite(9, LOW);
   delay(200);
   digitalWrite(5, HIGH);
   delay(200);
   digitalWrite(5, LOW);
   digitalWrite(4, HIGH);
   delay(200);
   digitalWrite(4, LOW);
   digitalWrite(3, HIGH);
   delay(200);
   digitalWrite(3, LOW);
   digitalWrite(2, HIGH);
   digitalWrite(2, LOW);
   delay(250);
   digitalWrite(2, HIGH);
   digitalWrite(3, HIGH);
   digitalWrite(4, HIGH);  
   digitalWrite(5, HIGH);  
   digitalWrite(6, HIGH);  
   digitalWrite(7, HIGH);  
   digitalWrite(8, HIGH);  
   digitalWrite(9, HIGH);
   delay(100);
   digitalWrite(2, LOW);
   digitalWrite(3, LOW);
   digitalWrite(4, LOW);  
   digitalWrite(5, LOW);  
   digitalWrite(6, LOW);  
   digitalWrite(7, LOW);  
   digitalWrite(8, LOW);  
   digitalWrite(9, LOW);
   delay(1320);
   digitalWrite(9, HIGH);
//0:19(start)
   delay(50);
   digitalWrite(2, HIGH);
   digitalWrite(3, HIGH);
   digitalWrite(4, HIGH);  
   digitalWrite(5, HIGH);  
   digitalWrite(6, HIGH);  
   digitalWrite(7, HIGH);  
   digitalWrite(8, HIGH);  
   digitalWrite(9, HIGH);
   delay(50); 
   digitalWrite(2, LOW);
   digitalWrite(3, LOW);
   digitalWrite(4, LOW);  
   digitalWrite(5, LOW);  
   digitalWrite(6, LOW);  
   digitalWrite(7, LOW);  
   digitalWrite(8, LOW);  
   digitalWrite(9, LOW);
   delay(400);
   digitalWrite(9, LOW);
   delay(50);
   digitalWrite(2, HIGH);
   delay(700);
   digitalWrite(2, LOW);
   digitalWrite(2, HIGH);
   digitalWrite(3, HIGH);
   digitalWrite(4, HIGH);  
   digitalWrite(5, HIGH);  
   digitalWrite(6, HIGH);  
   digitalWrite(7, HIGH);  
   digitalWrite(8, HIGH);  
   digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
   digitalWrite(3, LOW);
   digitalWrite(4, LOW);  
   digitalWrite(5, LOW);  
   digitalWrite(6, LOW);  
   digitalWrite(7, LOW);  
   digitalWrite(8, LOW);  
   digitalWrite(9, LOW);
   delay(50);
   digitalWrite(8, HIGH);
   delay(700);
   digitalWrite(8, LOW);
   digitalWrite(3, HIGH);
   delay(200);
   digitalWrite(3, LOW);
   digitalWrite(2, HIGH);
   digitalWrite(3, HIGH);
   digitalWrite(4, HIGH);  
   digitalWrite(5, HIGH);  
   digitalWrite(6, HIGH);  
   digitalWrite(7, HIGH);  
   digitalWrite(8, HIGH);  
   digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
   digitalWrite(3, LOW);
   digitalWrite(4, LOW);  
   digitalWrite(5, LOW);  
   digitalWrite(6, LOW);  
   digitalWrite(7, LOW);  
   digitalWrite(8, LOW);  
   digitalWrite(9, LOW);
   delay(50);
   digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
   delay(50);
  digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
   delay(50);
    digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
   delay(50);
  digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
   delay(50);
   digitalWrite(4, HIGH);
   delay(200);
   digitalWrite(4, LOW);
   digitalWrite(5, HIGH);
   delay(200);
   digitalWrite(5, LOW);
   digitalWrite(6, HIGH);
   delay(200);
//0:21 BEAT
  digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
   delay(70);
   digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
   delay(70);
   digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
   delay(70);
   digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
   delay(70);
  digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
   delay(70);
   digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
   delay(70);
  digitalWrite(5, HIGH);
  digitalWrite(6, HIGH);
  delay(200);
  digitalWrite(5, LOW);
  digitalWrite(6, LOW);
  delay(200);
   digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
   delay(70);
  digitalWrite(4, HIGH);
  digitalWrite(7, HIGH);
  delay(200);
  digitalWrite(4, LOW);
  digitalWrite(7, LOW);
  delay(200);
  digitalWrite(3, HIGH);
  digitalWrite(8, HIGH);
  delay(200);
  digitalWrite(3, LOW);
  digitalWrite(8, LOW);
  delay(200);
  digitalWrite(2, HIGH);
  digitalWrite(9, HIGH);
  delay(200);
   digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
   delay(70);
  digitalWrite(2, LOW);
  digitalWrite(9, LOW);
  delay(200);
  digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
   delay(70);
  digitalWrite(2, HIGH);
  digitalWrite(3, HIGH);
  delay(100);
  digitalWrite(2, LOW);
  digitalWrite(3, LOW);
  delay(100);
  digitalWrite(9, HIGH);
  digitalWrite(8, HIGH);
  delay(100);
  digitalWrite(9, LOW);
  digitalWrite(8, LOW);
  delay(100);
  digitalWrite(4, HIGH);
  digitalWrite(5, HIGH);
  delay(100);
  digitalWrite(4, LOW);
  digitalWrite(5, LOW);
  delay(100);
  digitalWrite(7, HIGH);
  digitalWrite(6, HIGH);
  delay(100);
  digitalWrite(7, LOW);
  digitalWrite(6, LOW);
  delay(100);
   digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
   delay(70);
  digitalWrite(2, HIGH);
  digitalWrite(3, HIGH);
  digitalWrite(4, HIGH);
  digitalWrite(5, HIGH);
  digitalWrite(6, HIGH);
  digitalWrite(7, HIGH);
  digitalWrite(8, HIGH);
  digitalWrite(9, HIGH);
  delay(50);
  digitalWrite(2, LOW);
  digitalWrite(3, LOW);
  digitalWrite(4, LOW);
  digitalWrite(5, LOW);
  digitalWrite(6, LOW);
  digitalWrite(7, LOW);
  digitalWrite(8, LOW);
  digitalWrite(9, LOW);
  delay(70);
   digitalWrite(2, HIGH);
  digitalWrite(3, HIGH);
  digitalWrite(4, HIGH);
  digitalWrite(5, HIGH);
  digitalWrite(6, HIGH);
  digitalWrite(7, HIGH);
  digitalWrite(8, HIGH);
  digitalWrite(9, HIGH);
  delay(50);
  digitalWrite(2, LOW);
  digitalWrite(3, LOW);
  digitalWrite(4, LOW);
  digitalWrite(5, LOW);
  digitalWrite(6, LOW);
  digitalWrite(7, LOW);
  digitalWrite(8, LOW);
  digitalWrite(9, LOW);
  delay(50);
   digitalWrite(2, HIGH);
  digitalWrite(3, HIGH);
  digitalWrite(4, HIGH);
  digitalWrite(5, HIGH);
  digitalWrite(6, HIGH);
  digitalWrite(7, HIGH);
  digitalWrite(8, HIGH);
  digitalWrite(9, HIGH);
  delay(70);
  digitalWrite(2, LOW);
  digitalWrite(3, LOW);
  digitalWrite(4, LOW);
  digitalWrite(5, LOW);
  digitalWrite(6, LOW);
  digitalWrite(7, LOW);
  digitalWrite(8, LOW);
  digitalWrite(9, LOW);
  delay(70);
  digitalWrite(2, HIGH);
  digitalWrite(3, HIGH);
  digitalWrite(4, HIGH);
  digitalWrite(5, HIGH);
  digitalWrite(6, HIGH);
  digitalWrite(7, HIGH);
  digitalWrite(8, HIGH);
  digitalWrite(9, HIGH);
  delay(70);
  digitalWrite(2, LOW);
  digitalWrite(3, LOW);
  digitalWrite(4, LOW);
  digitalWrite(5, LOW);
  digitalWrite(6, LOW);
  digitalWrite(7, LOW);
  digitalWrite(8, LOW);
  digitalWrite(9, LOW);
  delay(50);
  digitalWrite(2, HIGH);
  digitalWrite(3, HIGH);
  digitalWrite(4, HIGH);
  digitalWrite(5, HIGH);
  digitalWrite(6, HIGH);
  digitalWrite(7, HIGH);
  digitalWrite(8, HIGH);
  digitalWrite(9, HIGH);
  delay(70);
  digitalWrite(2, LOW);
  digitalWrite(3, LOW);
  digitalWrite(4, LOW);
  digitalWrite(5, LOW);
  digitalWrite(6, LOW);
  digitalWrite(7, LOW);
  digitalWrite(8, LOW);
  digitalWrite(9, LOW);
  delay(70);
   digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
   delay(50);
digitalWrite(3, HIGH);
  digitalWrite(8, HIGH);
  delay(200);
  digitalWrite(3, LOW);
  digitalWrite(8, LOW);
  delay(200);
  digitalWrite(4, HIGH);
  digitalWrite(7, HIGH);
  delay(200);
  digitalWrite(4, LOW);
  digitalWrite(7, LOW);
  delay(200);
  digitalWrite(5, HIGH);
  digitalWrite(6, HIGH);
  delay(200);
  digitalWrite(5, LOW);
  digitalWrite(6, LOW);
  delay(200);
  digitalWrite(2, HIGH);
  digitalWrite(9, HIGH);
  delay(200);
  digitalWrite(2, LOW);
  digitalWrite(9, LOW);
  delay(200);
  digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
   delay(50);
   digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
   delay(50);
   digitalWrite(3, HIGH);
  digitalWrite(4, HIGH);
  digitalWrite(7, HIGH);
  digitalWrite(8, HIGH);
  delay(200);
  digitalWrite(3, LOW);
  digitalWrite(4, LOW);
  digitalWrite(7, LOW);
  digitalWrite(8, LOW);
  delay(200);
  digitalWrite(5, HIGH);
  digitalWrite(6, HIGH);
  delay(200);
  digitalWrite(5, LOW);
  digitalWrite(6, LOW);
  delay(200);
  digitalWrite(2, HIGH);
  digitalWrite(9, HIGH);
  delay(200);
  digitalWrite(2, LOW);
  digitalWrite(9, LOW);
  delay(200);
  digitalWrite(2, HIGH);
  digitalWrite(9, HIGH);
  delay(200);
  digitalWrite(2, LOW);
  digitalWrite(9, LOW);
  delay(200);
  digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
   delay(70);
   digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
   delay(70);
   digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
   delay(70);
digitalWrite(2, HIGH);
  digitalWrite(3, HIGH);
  digitalWrite(4, HIGH);
  digitalWrite(5, HIGH);
  delay(300);
  digitalWrite(2, LOW);
  digitalWrite(3, LOW);
  digitalWrite(4, LOW);
  digitalWrite(5, LOW);
  delay(300);
  digitalWrite(9, HIGH);
  digitalWrite(8, HIGH);
  digitalWrite(7, HIGH);
  digitalWrite(6, HIGH);
  delay(300);
  digitalWrite(9, LOW);
  digitalWrite(8, LOW);
  digitalWrite(7, LOW);
  digitalWrite(6, LOW);
    digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
      digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
  digitalWrite(2, HIGH);
  delay(100);
  digitalWrite(3, HIGH);
  delay(100);
  digitalWrite(4, HIGH);
  delay(100);
  digitalWrite(9, HIGH);
  delay(100);
  digitalWrite(8, HIGH);
  delay(100);
  digitalWrite(7, HIGH);
  delay(100);
  digitalWrite(5, HIGH);
  delay(50);
  digitalWrite(5, LOW);
  delay(80);
  digitalWrite(6, HIGH);
  delay(50);
  digitalWrite(6, LOW);
  delay(80);
  digitalWrite(5, HIGH);
  delay(50);
  digitalWrite(5, LOW);
  delay(80);
  digitalWrite(6, HIGH);
  delay(50);
  digitalWrite(6, LOW);
  delay(80);
  digitalWrite(5, HIGH);
  delay(50);
  digitalWrite(5, LOW);
  delay(80);
  digitalWrite(6, HIGH);
  delay(50);
  digitalWrite(6, LOW);
  delay(80);
  digitalWrite(2, LOW);
  delay(100);
  digitalWrite(9, LOW);
  delay(100);
  digitalWrite(3, LOW);
  delay(100);
  digitalWrite(8, LOW);
  delay(100);
  digitalWrite(4, LOW);
  delay(100);
  digitalWrite(7, LOW);
  delay(100);
  digitalWrite(5, LOW);
  digitalWrite(6, LOW);
  //0:31
  digitalWrite(3, HIGH);
  delay(50);
  digitalWrite(3, LOW);
  digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
 digitalWrite(7, HIGH);
 delay(100);
 digitalWrite(7, LOW);
 digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
 digitalWrite(4, HIGH);
 delay(100);
 digitalWrite(4, LOW);
 digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
 digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
 digitalWrite(2, HIGH);
 delay(200);
 digitalWrite(2, LOW);
 digitalWrite(3, HIGH);
 delay(200);
 digitalWrite(3, LOW);
 digitalWrite(4, HIGH);
 delay(200);
 digitalWrite(4, LOW);
 digitalWrite(5, HIGH);
 delay(200);
 digitalWrite(5, LOW);
 digitalWrite(6, HIGH);
 delay(200);
 digitalWrite(6, LOW);
 digitalWrite(7, HIGH);
 delay(200);
 digitalWrite(7, LOW);
 digitalWrite(8, HIGH);
 delay(200);
 digitalWrite(8, LOW);
 digitalWrite(9, HIGH);
 delay(200);
 digitalWrite(9, LOW);
 digitalWrite(8, HIGH);
 delay(200);
 digitalWrite(8, LOW);
 digitalWrite(7, HIGH);
 delay(200);
 digitalWrite(7, LOW);
 digitalWrite(6, HIGH);
 delay(200);
 digitalWrite(6, LOW);
 digitalWrite(5, HIGH);
 delay(200);
 digitalWrite(5, LOW);
 digitalWrite(4, HIGH);
 delay(200);
 digitalWrite(4, LOW);
 digitalWrite(3, HIGH);
 delay(200);
 digitalWrite(3, LOW);
 digitalWrite(2, HIGH);
digitalWrite(6, HIGH);
delay(200);
digitalWrite(6, LOW);
  digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
digitalWrite(9, HIGH);
delay(100);
digitalWrite(9, LOW);
  digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
digitalWrite(2, HIGH);
delay(100);
digitalWrite(2, LOW);
  digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
digitalWrite(5, HIGH);
delay(100);
digitalWrite(5, LOW);
delay(100);
digitalWrite(7, HIGH);
delay(100);
digitalWrite(7, LOW);
delay(50);
  digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
  //0:35(Keys and Beats)
  digitalWrite(5, HIGH);
  delay(100);
  digitalWrite(5, LOW);
  delay(50);
  digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
    digitalWrite(3, HIGH);
  delay(100);
  digitalWrite(3, LOW);
  delay(50);
  digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
    digitalWrite(2, HIGH);
  delay(100);
  digitalWrite(2, LOW);
  delay(50);
  digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
    digitalWrite(8, HIGH);
    delay(100);
    digitalWrite(8, LOW);
    delay(50);
  digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
    digitalWrite(2, HIGH);
    delay(100);
    digitalWrite(2, LOW);
    delay(50);
    digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
    digitalWrite(9, HIGH);
    delay(100);
    digitalWrite(9, LOW);
    delay(50);
    digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
    digitalWrite(4, HIGH);
    delay(100);
    digitalWrite(4, LOW);
    delay(50);
    digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
    digitalWrite(6, HIGH);
    delay(100);
    digitalWrite(6, LOW);
    delay(50);
    digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
    digitalWrite(8, HIGH);
    delay(150);
    digitalWrite(8, LOW);
    delay(150);
    digitalWrite(6, HIGH);
    delay(150);
    digitalWrite(6, LOW);
    digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
    digitalWrite(5, HIGH);
    delay(150);
    digitalWrite(5, LOW);
    delay(150);
    digitalWrite(3, HIGH);
    delay(150);
    digitalWrite(3, LOW);
    digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
    digitalWrite(6, HIGH);
    delay(100);
    digitalWrite(6, LOW);
    delay(50);
    digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
    digitalWrite(4, HIGH);
    delay(100);
    digitalWrite(4, LOW);
    delay(50);
    digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
    delay(50);
    digitalWrite(4, HIGH);
    delay(100);
    digitalWrite(4, LOW);
    delay(150);
    digitalWrite(6, HIGH);
    delay(150);
    digitalWrite(6, LOW);
    delay(150);
    digitalWrite(2, HIGH);
    digitalWrite(2, LOW);
    digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(4, HIGH);
   delay(100);
   digitalWrite(4, LOW);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
    digitalWrite(4, HIGH);
    delay(100);
    digitalWrite(4, LOW);
    delay(100);
    digitalWrite(5, HIGH);
    delay(100);
    digitalWrite(5, LOW);
    delay(50);
    digitalWrite(8, HIGH);
    delay(150);
    digitalWrite(8, LOW);
    delay(150);
    digitalWrite(5, HIGH);
    delay(150);
    digitalWrite(5, LOW);
    digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
    digitalWrite(5, HIGH);
    delay(150);
    digitalWrite(5, LOW);
    delay(150);
    digitalWrite(7, HIGH);
    delay(150);
    digitalWrite(7, LOW);
    digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);  
    digitalWrite(5, HIGH);  
    digitalWrite(6, HIGH);  
    digitalWrite(7, HIGH);  
    digitalWrite(8, HIGH);  
    digitalWrite(9, HIGH);
   delay(80);
   digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
   digitalWrite(2, HIGH);
   delay(700);
   digitalWrite(2, LOW);
   digitalWrite(3, HIGH);
   delay(700);
   digitalWrite(3, LOW);
   digitalWrite(4, HIGH);
   delay(200);
   digitalWrite(4, LOW);
   digitalWrite(5, HIGH);
   delay(200);
   digitalWrite(5, LOW);
   digitalWrite(6, HIGH);
   delay(200);
   digitalWrite(6, LOW);
   digitalWrite(7, HIGH);
   delay(200);
   digitalWrite(7, LOW);
   digitalWrite(8, HIGH);
   delay(700);
   digitalWrite(8, LOW);
   delay(700);
   digitalWrite(9, HIGH);
   digitalWrite(9, LOW);
   delay(700);
   digitalWrite(8, HIGH);
   delay(700);
   digitalWrite(8, LOW);
   digitalWrite(7, HIGH);
   delay(700);
   digitalWrite(7, LOW);
   digitalWrite(6, HIGH);
   delay(200);
   digitalWrite(6, LOW);
   digitalWrite(5, HIGH);
   delay(200);
   digitalWrite(5, LOW);
   digitalWrite(4, HIGH);
   delay(400);
   digitalWrite(4, LOW);
   digitalWrite(3, HIGH);
   delay(400);
   digitalWrite(3, LOW);
   digitalWrite(2, HIGH);
   delay(1500);
   digitalWrite(2, LOW);
   
  }else if(switchVal == HIGH){
    digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);  
    digitalWrite(5, LOW);  
    digitalWrite(6, LOW);  
    digitalWrite(7, LOW);  
    digitalWrite(8, LOW);  
    digitalWrite(9, LOW);
  }
}
